# Generated by Django 5.2.8 on 2025-11-29 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluntariado', '0002_fotoevento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evento',
            options={'ordering': ['fecha'], 'verbose_name': 'Evento', 'verbose_name_plural': 'Eventos'},
        ),
        migrations.AlterModelOptions(
            name='voluntario',
            options={'ordering': ['-id'], 'verbose_name': 'Voluntario', 'verbose_name_plural': 'Voluntarios'},
        ),
        migrations.AlterField(
            model_name='evento',
            name='descripcion',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='fecha',
            field=models.DateField(verbose_name='Fecha del Evento'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='titulo',
            field=models.CharField(max_length=255, verbose_name='Título del Evento'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='voluntarios',
            field=models.ManyToManyField(blank=True, related_name='eventos', to='voluntariado.voluntario'),
        ),
        migrations.AlterField(
            model_name='voluntario',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='voluntario',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono'),
        ),
    ]
