# Generated by Django 5.2.8 on 2025-11-29 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluntariado', '0003_alter_evento_options_alter_voluntario_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voluntario',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='perfiles_voluntarios/', verbose_name='Foto de Perfil'),
        ),
    ]
