# Generated by Django 5.2.8 on 2025-11-29 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluntariado', '0004_voluntario_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='aforo',
            field=models.PositiveIntegerField(default=10, verbose_name='Aforo Máximo'),
        ),
    ]
